
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRUDAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeDetail
{

    public int EmpId { get; set; }

    public string EmpName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Address { get; set; }

    public string Dept { get; set; }

    public string Role { get; set; }

    public string Skills { get; set; }

    public Nullable<System.DateTime> DateOfJoin { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
